[Service]
EnvironmentFile=-/etc/rwoo/rwoo.env
EnvironmentFile=-/etc/rwoo/rwoo-release.env
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
ReadWritePaths=/var/lib/rwoo /var/cache/rwoo
